using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using InventoryBackend.Models;
using InventoryBackend.Utils;
using System.Data;
using System.Text.Json;

namespace InventoryBackend.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PurchaseOrdersController : ControllerBase
    {
        private readonly string _connectionString;
        public PurchaseOrdersController(IConfiguration config) => _connectionString = config.GetConnectionString("DefaultConnection")!;

        [HttpGet]
        public async Task<IActionResult> GetAsync()
        {
            try
            {
                var list = new List<PurchaseOrderResponse>();
                using (var conn = new MySqlConnection(_connectionString))
                using (var cmd = new MySqlCommand("sp_GetAllPurchaseOrders", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    await conn.OpenAsync();
                    using (var reader = await cmd.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            var po = new PurchaseOrderResponse
                            {
                                PurchaseOrderID = Convert.ToInt32(reader["PurchaseOrderID"]),
                                SupplierID = Convert.ToInt32(reader["SupplierID"]),
                                SupplierName = reader["SupplierName"].ToString(),
                                PurchaseDate = Convert.ToDateTime(reader["PurchaseDate"]).ToString("yyyy-MM-dd"),
                                ReceivedDate = reader["ReceivedDate"] != DBNull.Value ? Convert.ToDateTime(reader["ReceivedDate"]).ToString("yyyy-MM-dd") : null,
                                DeliveryStatus = reader["DeliveryStatus"].ToString(),
                                CreatedBy = Convert.ToInt32(reader["CreatedBy"]),
                                CreatedByName = reader["CreatedByName"].ToString(),
                                ReceivedBy = reader["ReceivedBy"] != DBNull.Value ? Convert.ToInt32(reader["ReceivedBy"]) : null
                            };

                            // Deserializing the nested JSON array generated by MySQL
                            string detailsJson = reader["DetailsJSON"] != DBNull.Value ? reader["DetailsJSON"].ToString() : "[]";
                            po.Details = JsonSerializer.Deserialize<List<PurchaseOrderItemResponse>>(detailsJson, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? new List<PurchaseOrderItemResponse>();

                            list.Add(po);
                        }
                    }
                }
                return Ok(list);
            }
            catch (MySqlException ex) { return this.HandleDbError(ex); }
        }

        [HttpPost]
        public async Task<IActionResult> PostAsync([FromBody] PurchaseOrderRequest request)
        {
            try
            {
                string itemsJson = JsonSerializer.Serialize(request.Details);
                using (var conn = new MySqlConnection(_connectionString))
                using (var cmd = new MySqlCommand("sp_CreatePurchaseOrder", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@p_SupplierID", request.SupplierID);
                    cmd.Parameters.AddWithValue("@p_PurchaseDate", request.PurchaseDate);
                    cmd.Parameters.AddWithValue("@p_DeliveryStatus", "Pending");
                    cmd.Parameters.AddWithValue("@p_CreatedBy", request.CreatedBy);
                    cmd.Parameters.AddWithValue("@p_ItemsJSON", itemsJson);
                    await conn.OpenAsync();
                    await cmd.ExecuteNonQueryAsync();
                }
                return Ok(new { message = "Order created!" });
            }
            catch (MySqlException ex) { return this.HandleDbError(ex); }
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> PutAsync(int id, [FromBody] PurchaseOrderRequest request)
        {
            try
            {
                string itemsJson = JsonSerializer.Serialize(request.Details);
                using (var conn = new MySqlConnection(_connectionString))
                using (var cmd = new MySqlCommand("sp_UpdatePurchaseOrder", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@p_OrderID", id);
                    cmd.Parameters.AddWithValue("@p_SupplierID", request.SupplierID);
                    cmd.Parameters.AddWithValue("@p_PurchaseDate", request.PurchaseDate);
                    cmd.Parameters.AddWithValue("@p_ReceivedDate", string.IsNullOrEmpty(request.ReceivedDate) ? DBNull.Value : request.ReceivedDate);
                    cmd.Parameters.AddWithValue("@p_DeliveryStatus", request.DeliveryStatus);
                    cmd.Parameters.AddWithValue("@p_ReceivedBy", request.ReceivedBy == null ? DBNull.Value : request.ReceivedBy);
                    cmd.Parameters.AddWithValue("@p_ItemsJSON", itemsJson);
                    await conn.OpenAsync();
                    await cmd.ExecuteNonQueryAsync();
                }
                return Ok(new { message = "Order updated!" });
            }
            catch (MySqlException ex) { return this.HandleDbError(ex); }
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            try
            {
                using (var conn = new MySqlConnection(_connectionString))
                using (var cmd = new MySqlCommand("sp_DeletePurchaseOrder", conn))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@p_OrderID", id);
                    await conn.OpenAsync();
                    await cmd.ExecuteNonQueryAsync();
                }
                return Ok(new { message = "Order deleted!" });
            }
            catch (MySqlException ex) { return this.HandleDbError(ex); }
        }
    }
}